#!/bin/bash

# Agent Kit Installation Script
# Creates global aliases for agent-kit CLI

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the absolute path of the project directory
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_PATH="$PROJECT_DIR/src/cli.ts"

echo -e "${BLUE}🚀 Agent Kit Installation${NC}"
echo -e "${BLUE}=========================${NC}"

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js is not installed. Please install Node.js first.${NC}"
    exit 1
fi

# Check if TypeScript is available (tsx or ts-node)
if ! command -v tsx &> /dev/null && ! command -v ts-node &> /dev/null; then
    echo -e "${YELLOW}⚠️  tsx or ts-node not found. Installing tsx globally...${NC}"
    npm install -g tsx
fi

# Determine which TypeScript runner to use
if command -v tsx &> /dev/null; then
    TS_RUNNER="tsx"
elif command -v ts-node &> /dev/null; then
    TS_RUNNER="ts-node"
else
    echo -e "${RED}❌ Could not install TypeScript runner. Please install tsx or ts-node manually.${NC}"
    exit 1
fi

# Check if CLI file exists
if [ ! -f "$CLI_PATH" ]; then
    echo -e "${RED}❌ CLI file not found at: $CLI_PATH${NC}"
    exit 1
fi

# Determine shell configuration file
SHELL_CONFIG=""
if [ -n "$ZSH_VERSION" ] || [ "$SHELL" = "/bin/zsh" ] || [ "$SHELL" = "/usr/bin/zsh" ]; then
    SHELL_CONFIG="$HOME/.zshrc"
elif [ -n "$BASH_VERSION" ] || [ "$SHELL" = "/bin/bash" ] || [ "$SHELL" = "/usr/bin/bash" ]; then
    SHELL_CONFIG="$HOME/.bashrc"
else
    # Try to detect based on existing files
    if [ -f "$HOME/.zshrc" ]; then
        SHELL_CONFIG="$HOME/.zshrc"
    elif [ -f "$HOME/.bashrc" ]; then
        SHELL_CONFIG="$HOME/.bashrc"
    else
        echo -e "${RED}❌ Could not determine shell configuration file.${NC}"
        echo -e "${YELLOW}Please manually add the following aliases to your shell configuration:${NC}"
        echo -e "${GREEN}alias agent-kit='$TS_RUNNER $CLI_PATH'${NC}"
        echo -e "${GREEN}alias agentkit='$TS_RUNNER $CLI_PATH'${NC}"
        echo -e "${GREEN}alias ak='$TS_RUNNER $CLI_PATH'${NC}"
        exit 1
    fi
fi

echo -e "${BLUE}📁 Project directory: $PROJECT_DIR${NC}"
echo -e "${BLUE}🎯 CLI path: $CLI_PATH${NC}"
echo -e "${BLUE}🐚 Shell config: $SHELL_CONFIG${NC}"
echo -e "${BLUE}⚡ TypeScript runner: $TS_RUNNER${NC}"

# Create backup of shell config
cp "$SHELL_CONFIG" "$SHELL_CONFIG.backup.$(date +%Y%m%d_%H%M%S)"
echo -e "${GREEN}✅ Created backup of $SHELL_CONFIG${NC}"

# Check if aliases already exist
if grep -q "alias agent-kit=" "$SHELL_CONFIG" 2>/dev/null; then
    echo -e "${YELLOW}⚠️  agent-kit alias already exists. Removing old aliases...${NC}"
    # Remove existing agent-kit aliases
    sed -i '/alias agent-kit=/d' "$SHELL_CONFIG"
    sed -i '/alias agentkit=/d' "$SHELL_CONFIG"
    sed -i '/alias ak=/d' "$SHELL_CONFIG"
fi

# Add Agent Kit section header
echo "" >> "$SHELL_CONFIG"
echo "# Agent Kit CLI Aliases" >> "$SHELL_CONFIG"
echo "# Generated by install.sh on $(date)" >> "$SHELL_CONFIG"

# Add aliases
echo "alias agent-kit='$TS_RUNNER $CLI_PATH'" >> "$SHELL_CONFIG"
echo "alias agentkit='$TS_RUNNER $CLI_PATH'" >> "$SHELL_CONFIG"
echo "alias ak='$TS_RUNNER $CLI_PATH'" >> "$SHELL_CONFIG"

echo -e "${GREEN}✅ Added aliases to $SHELL_CONFIG${NC}"

# Install dependencies if package.json exists
if [ -f "$PROJECT_DIR/package.json" ]; then
    echo -e "${BLUE}📦 Installing project dependencies...${NC}"
    cd "$PROJECT_DIR"
    
    if command -v pnpm &> /dev/null; then
        pnpm install
    elif command -v yarn &> /dev/null; then
        yarn install
    else
        npm install
    fi
    
    echo -e "${GREEN}✅ Dependencies installed${NC}"
fi

echo ""
echo -e "${GREEN}🎉 Installation completed successfully!${NC}"
echo ""
echo -e "${YELLOW}📋 Available commands:${NC}"
echo -e "  ${GREEN}agent-kit${NC} - Full command name"
echo -e "  ${GREEN}agentkit${NC}  - Short version"
echo -e "  ${GREEN}ak${NC}        - Shortest alias"
echo ""
echo -e "${YELLOW}🔄 To use the aliases immediately, run:${NC}"
echo -e "  ${GREEN}source $SHELL_CONFIG${NC}"
echo ""
echo -e "${YELLOW}📖 Or restart your terminal and try:${NC}"
echo -e "  ${GREEN}agent-kit --help${NC}"
echo -e "  ${GREEN}agentkit init${NC}"
echo -e "  ${GREEN}ak list${NC}"
echo ""
echo -e "${BLUE}🚀 Happy coding with Agent Kit!${NC}"
